# Generated by Django 5.1.2 on 2024-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
                ('detalles', models.CharField(blank=True, max_length=1000, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
